### ISSUE TITLE
Multiple ilo_hosts?

### ISSUE THREAD

**Issue by Marf97** [hpilo-exporter/hpilo-exporter#4]
Hi, is it available to have multiple ilo_hosts in one running instance of hpilo-exporter? would be nice feature since I would like to run hpilo-exporter on one machine, grabbing metrics from all iLo machines and then publishing them in prometheus. I was looking at implementation of exporter.py and it seems that it does not contain any parsing of multiple IP addresses in ilo_host variable.

**Comment by srkaviani** [comment]
Hi
You can define all of your hp ilo targets in prometheus.yml file such as sample code. Prometheus will manage this and gets metrics from hpilo-exporter per instance of ilos and you don't need to run more than one instance of hpilo-exporter. 

```
- job_name: 'hpilo'
  scrape_interval: 1m
  scrape_timeout: 30s
  params: 
    ilo_host: ['']
    #ilo_port: ['443']                 # may be set in exporter ENV
    #ilo_user: ['my_ilo_user']         # may be set in exporter ENV
    #ilo_password: ['my_ilo_password'] # may be set in exporter ENV
  static_configs:
    - targets:
      - ilo1_fqdn.domain
      - ilo2_fqdn.domain
      - ilo3_fqdn.domain
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_ilo_host
    - source_labels: [__param_ilo_host]
      target_label: ilo_host
    - target_label: __address__
      replacement: 127.0.0.1:9416  # hpilo exporter.
```
