### ISSUE TITLE
module 'prometheus_metrics' has no attribute 'gauges'

### ISSUE THREAD

**Issue by mmmmmmmmmpppp** [hpilo-exporter/hpilo-exporter#5]
Hello everyone,

I installed the required packages and downloaded/installed your code manually
Perhaps it is way to early to test but this is the error I got :

File "/usr/local/lib/python3.9/dist-packages/hpilo_exporter/exporter.py", line 107, in do_GET
    prometheus_metrics.gauges[gauge].labels(product_name=product_name,
AttributeError: module 'prometheus_metrics' has no attribute 'gauges'

Thank you for the good work.
Always willing to test !

**Comment by srkaviani** [comment]
Hi,
Please explain the steps you followed for installation to check.

**Comment by mmmmmmmmmpppp** [comment]
Hi,


The installation process is not clean I'm afraid as I did a lot of trial and error testing. I could uninstall all python packages or even reinstall the OS if it helps. 
Below a short description of the installation and way down extracts of pip list

I use a RPi4 to test Prometheus with its different exporters
I stumbled on hpilo-exporter 0.4.5 (https://pypi.org/project/hpilo-exporter/)
Which I use to monitor - iLO5 for a ProLiant DL380 Gen10
As I will use more than one exporter type I tried to place them all in dedicated folders.
I am new to PIP and the documentation did not help.
So after a few installs and uninstalls I concluded that this was not possible for the hpilo... package
And accepted the default installation, and added the required other packages.

Testing with curl gave no errors but no metrics were returned.
And then I stumbled on this projects.

I downloaded the code, unzipped in the home folder and ran setup.
Testing finally resulted in the issue

=================================================================================

uncomplete history
-----------------------
 1108  sudo python3 -m pip install --upgrade pip setuptools wheel
 1109  python3 -m pip install --upgrade pip setuptools wheel
 1191  pip install prometheus-metrics




$ pip list
-------------
Package            Version   Editable project location
------------------ --------- --------------------------------------
...
hpilo-exporter     0.4.5     /usr/local/lib/python3.9/dist-packages
.....
pip                23.1.2
prometheus-client  0.16.0
prometheus-metrics 0.1.6.6
....
python-hpilo       4.4.3
...
setuptools         67.7.2
....
Werkzeug           1.0.1
wheel              0.40.0
....

**Comment by srkaviani** [comment]
first uninstall older versions of hpilo_exporter. 
the new version is not yet uploaded to https://pypi.org/.
Please follow this instruction to install hpilo_exporter latest version:
```
cd /opt
git clone https://github.com/hpilo-exporter/hpilo-exporter/
pip install /opt/hpilo-exporter
```

**Comment by mmmmmmmmmpppp** [comment]
Ok, it works now 
(i needed to add sudo but that is probably related with permissions on rasbian)

I will try in the next step to configure alerts for multiple ProLiant using your exporter

Thank you very much for your quick help !
Feel free to contact if you need un beta tester

Cheers
M

**Comment by jhonyh** [comment]
Hi Sri.

I read your reply the installation below that I tried to follow it but need your help in the next steps:
cd /opt
git clone https://github.com/hpilo-exporter/hpilo-exporter/
pip install /opt/hpilo-exporter

I used the pip3 and it is installed in /opt:
[root@grafaprome opt]# ls
containerd  hpilo-exporter  rh
[root@grafaprome opt]#

what else the next step to make it running and collect the ilo metrics from some servers and exproted to the prometheus?
I had so many times install from may forks but still failed with error:
[root@grafaprome ~]# docker run -p 9416:9416 hpilo-exporter:latest
Starting exporter on: http://0.0.0.0:9416/metrics
Press Ctrl+C to quit
missing parameter 'ilo_host'
10.212.70.200 - - [07/Aug/2023 22:28:18] "GET /metrics HTTP/1.1" 500 -
missing parameter 'ilo_host'
10.212.70.200 - - [07/Aug/2023 22:28:33] "GET /metrics HTTP/1.1" 500 -
missing parameter 'ilo_host'
10.212.70.200 - - [07/Aug/2023 22:28:48] "GET /metrics HTTP/1.1" 500 -

How to solve it? or any how to make it running in local or docker to scrap the metrics from multiple host to the prometheus host (10.212.70.200)?

many thanks for kind help in advance
Jhony

**Comment by srkaviani** [comment]
According to logs, you don't send ilo_host parameter and this is the reason of 500 error. 
Please Use this sample in your prometheus config to add your hp targets:
```
  #hp ilo
  - job_name: 'hpilo-exporter'
    scrape_interval: 2m
    scrape_timeout:  2m
    params:
      ilo_port: ['443']
      ilo_user: ['USER']                          ##### Replace USER with your ILO Username
      ilo_password: ['PASSWORD']       ##### Replace PASSWORD with your ILO Password
    static_configs:
    - targets: ['1.2.3.4']                         ##### Replace 1.2.3.4 with your ILO IP Address
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_ilo_host
      - source_labels: [__param_ilo_host]
        target_label: ilo_host
      - target_label: __address__
        replacement: 127.0.0.1:9416  # hpilo exporter.   ####### Replace 127.0.0.1 with ip of where hpilo_exporter installed.

```

Or , If you want just test connection of exporter to your targets you can check this address in your browser or you can send GET Request to it from CURL:
` http://1.1.1.1:9416/metrics?ilo_host=1.2.3.4&ilo_password=PASSWORD&ilo_port=443&ilo_user=USER`
Replace 1.1.1.1 with ip of where hpilo_exporter installed, Replace 1.2.3.4 with your ILO IP Address , Replace USER with your ILO Username , Replace PASSWORD with your ILO Password ,
