### ISSUE TITLE
Please help on how to write the prometheus.yml

### ISSUE THREAD

**Issue by jhonyh** [hpilo-exporter/hpilo-exporter#8]
Hi
You can define all of your hp ilo targets in prometheus.yml file such as sample code. Prometheus will manage this and gets metrics from hpilo-exporter per instance of ilos and you don't need to run more than one instance of hpilo-exporter. 

```
- job_name: 'hpilo'
  scrape_interval: 1m
  scrape_timeout: 30s
  params: 
    ilo_host: ['']
    #ilo_port: ['443']                 # may be set in exporter ENV
    #ilo_user: ['my_ilo_user']         # may be set in exporter ENV
    #ilo_password: ['my_ilo_password'] # may be set in exporter ENV
  static_configs:
    - targets:
      - ilo1_fqdn.domain
      - ilo2_fqdn.domain
      - ilo3_fqdn.domain
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_ilo_host
    - source_labels: [__param_ilo_host]
      target_label: ilo_host
    - target_label: __address__
      replacement: 127.0.0.1:9416  # hpilo exporter.
```

_Originally posted by @srkaviani in https://github.com/hpilo-exporter/hpilo-exporter/issues/4#issuecomment-1550718841_
            

it was not worked on my server. my prometheus.yml  only work if i used as follows:

global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.212.70.200:9090']

  - job_name: 'alertmanager'
    static_configs:
    - targets: ['10.212.70.200:9093']

  - job_name: 'VSphere_Host'
    static_configs:
    - targets: ['10.212.70.200:9272']
      labels:
        alias: VMWare

  - job_name: 'hpilo-exporter'
    scrape_interval: 10s
    scrape_timeout: 30s
    static_configs:
    - targets:
      - 10.212.70.200:9416
      - 10.212.70.200:9516
      - 10.212.70.200:9716
      - 10.212.70.200:9816
      labels:
        alias: ILOs

alerting:
  alertmanagers:
  - static_configs:
    - targets: ['10.212.70.200:9093']

and to start the exporter I used this way:
docker run -it -d --restart unless-stopped  -p 9816:9416 -e ILO_HOST=10.117.3.118 -e ILO_USER=administrator -e ILO_PASSWORD=P@ssw0rd! -e ILO_PORT=443 --name hpilo-exporter-118 hpilo-exporter:latest &

I tried this setup but not worked:
[root@grafaprome prometheus]# cat hpilo-exporter.yml
 - job_name: 'hpilo-exporter'
   metrics_path:'/metrics'
   file_sd_configs:
    - files:
      - /etc/prometheus/hpilo.yml
 #   scrape_interval: 35s
   scrape_interval: 1m
   scrape_timeout: 30s
   params:
    - section: [hpilo]
   ilo_host: ['10.117.3.111', '10.117.3.116'. '10.117.3.117'. '10.117.3.118']
   ilo_port: ['443']
   ilo_user: ['administrator']
   ilo_password: ['P@ssw0rd!']
   #file_sd_configs:
   # - files:
   #  - 'hpilo.yml'
   relabel_configs:
   - source_labels: [__address__]
     target_label: __param_ilo_host
   - source_labels: [__param_ilo_host]
     target_label: ilo_host
   - target_label: __address__
     replacement: 10.212.70.200:9416  # hpilo exporter
#     replacement: 10.212.70.200:9516  # hpilo exporter
#     replacement: 10.212.70.200:9616  # hpilo exporter
#     replacement: 10.212.70.200:9716  # hpilo exporter

# HPILO
  - job_name: 'HPILO'
    metrics_path:'/metrics'
    static_configs:
      - targets:
        - '10.117.3.111'
        - '10.117.3.116'
        - '10.117.3.117'
        - '10.117.3.118'
    params:
      section: [HPILO]
    relabel_configs:
    - source_labels: [__address__]
      target_label: __param_ilo_host
    - source_labels: [__param_ilo_host]
      target_label: ilo_host
    - target_label: __address__
      replacement: 10.212.70.200:9416  # hpilo exporter
#      replacement: 10.212.70.200:9516  # hpilo exporter
#      replacement: 10.212.70.200:9616  # hpilo exporter
#      replacement: 10.212.70.200:9716  # hpilo exporter

Please advice
